[package]
name = "data-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
reduct-base = "1.16.0"
reduct-rs = "1.16.0"
tokio = "1.40.0"
simple_logger = "5.0.0"
log = "0.4.22"
rand = "0.8.4"
md5 = "0.8.0"
futures-util = "0.3.31"